window.esdocSearchIndex = [
  [
    "samp.js/javascript/buffer.js~buffer",
    "class/javascript/Buffer.js~Buffer.html",
    "<span>Buffer</span> <span class=\"search-result-import-path\">samp.js/javascript/Buffer.js</span>",
    "class"
  ],
  [
    "samp.js/javascript/event.js~event",
    "class/javascript/Event.js~Event.html",
    "<span>Event</span> <span class=\"search-result-import-path\">samp.js/javascript/Event.js</span>",
    "class"
  ],
  [
    "samp.js/javascript/events.js~events",
    "class/javascript/Events.js~Events.html",
    "<span>Events</span> <span class=\"search-result-import-path\">samp.js/javascript/Events.js</span>",
    "class"
  ],
  [
    "samp.js/javascript/filesystem.js~filesystem",
    "class/javascript/FileSystem.js~FileSystem.html",
    "<span>FileSystem</span> <span class=\"search-result-import-path\">samp.js/javascript/FileSystem.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "javascript/buffer.js",
    "file/javascript/Buffer.js.html",
    "javascript/Buffer.js",
    "file"
  ],
  [
    "javascript/buffer.js~buffer#buffer",
    "class/javascript/Buffer.js~Buffer.html#instance-member-buffer",
    "javascript/Buffer.js~Buffer#buffer",
    "member"
  ],
  [
    "javascript/buffer.js~buffer#constructor",
    "class/javascript/Buffer.js~Buffer.html#instance-constructor-constructor",
    "javascript/Buffer.js~Buffer#constructor",
    "method"
  ],
  [
    "javascript/buffer.js~buffer#toobject",
    "class/javascript/Buffer.js~Buffer.html#instance-method-toObject",
    "javascript/Buffer.js~Buffer#toObject",
    "method"
  ],
  [
    "javascript/buffer.js~buffer#tostring",
    "class/javascript/Buffer.js~Buffer.html#instance-method-toString",
    "javascript/Buffer.js~Buffer#toString",
    "method"
  ],
  [
    "javascript/buffer.js~buffer#touint16array",
    "class/javascript/Buffer.js~Buffer.html#instance-method-toUint16Array",
    "javascript/Buffer.js~Buffer#toUint16Array",
    "method"
  ],
  [
    "javascript/buffer.js~buffer#touint8array",
    "class/javascript/Buffer.js~Buffer.html#instance-method-toUint8Array",
    "javascript/Buffer.js~Buffer#toUint8Array",
    "method"
  ],
  [
    "javascript/buffer.js~buffer#tovalue",
    "class/javascript/Buffer.js~Buffer.html#instance-method-toValue",
    "javascript/Buffer.js~Buffer#toValue",
    "method"
  ],
  [
    "javascript/event.js",
    "file/javascript/Event.js.html",
    "javascript/Event.js",
    "file"
  ],
  [
    "javascript/event.js~event#constructor",
    "class/javascript/Event.js~Event.html#instance-constructor-constructor",
    "javascript/Event.js~Event#constructor",
    "method"
  ],
  [
    "javascript/event.js~event#fn",
    "class/javascript/Event.js~Event.html#instance-member-fn",
    "javascript/Event.js~Event#fn",
    "member"
  ],
  [
    "javascript/event.js~event#name",
    "class/javascript/Event.js~Event.html#instance-member-name",
    "javascript/Event.js~Event#name",
    "member"
  ],
  [
    "javascript/event.js~event#type",
    "class/javascript/Event.js~Event.html#instance-member-type",
    "javascript/Event.js~Event#type",
    "member"
  ],
  [
    "javascript/events.js",
    "file/javascript/Events.js.html",
    "javascript/Events.js",
    "file"
  ],
  [
    "javascript/events.js~events#addevent",
    "class/javascript/Events.js~Events.html#instance-method-addEvent",
    "javascript/Events.js~Events#addEvent",
    "method"
  ],
  [
    "javascript/events.js~events#constructor",
    "class/javascript/Events.js~Events.html#instance-constructor-constructor",
    "javascript/Events.js~Events#constructor",
    "method"
  ],
  [
    "javascript/events.js~events#fire",
    "class/javascript/Events.js~Events.html#instance-method-fire",
    "javascript/Events.js~Events#fire",
    "method"
  ],
  [
    "javascript/events.js~events#ids",
    "class/javascript/Events.js~Events.html#instance-member-ids",
    "javascript/Events.js~Events#ids",
    "member"
  ],
  [
    "javascript/events.js~events#off",
    "class/javascript/Events.js~Events.html#instance-method-off",
    "javascript/Events.js~Events#off",
    "method"
  ],
  [
    "javascript/events.js~events#on",
    "class/javascript/Events.js~Events.html#instance-method-on",
    "javascript/Events.js~Events#on",
    "method"
  ],
  [
    "javascript/events.js~events#one",
    "class/javascript/Events.js~Events.html#instance-method-one",
    "javascript/Events.js~Events#one",
    "method"
  ],
  [
    "javascript/events.js~events#some",
    "class/javascript/Events.js~Events.html#instance-method-some",
    "javascript/Events.js~Events#some",
    "method"
  ],
  [
    "javascript/filesystem.js",
    "file/javascript/FileSystem.js.html",
    "javascript/FileSystem.js",
    "file"
  ],
  [
    "javascript/filesystem.js~filesystem#appendfile",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-appendFile",
    "javascript/FileSystem.js~FileSystem#appendFile",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#close",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-close",
    "javascript/FileSystem.js~FileSystem#close",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#delete",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-delete",
    "javascript/FileSystem.js~FileSystem#delete",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#exits",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-exits",
    "javascript/FileSystem.js~FileSystem#exits",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#mkdir",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-mkdir",
    "javascript/FileSystem.js~FileSystem#mkdir",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#open",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-open",
    "javascript/FileSystem.js~FileSystem#open",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#read",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-read",
    "javascript/FileSystem.js~FileSystem#read",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#readfile",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-readFile",
    "javascript/FileSystem.js~FileSystem#readFile",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#readdir",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-readdir",
    "javascript/FileSystem.js~FileSystem#readdir",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#rename",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-rename",
    "javascript/FileSystem.js~FileSystem#rename",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#rmdir",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-rmdir",
    "javascript/FileSystem.js~FileSystem#rmdir",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#unlink",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-unlink",
    "javascript/FileSystem.js~FileSystem#unlink",
    "method"
  ],
  [
    "javascript/filesystem.js~filesystem#writefile",
    "class/javascript/FileSystem.js~FileSystem.html#instance-method-writeFile",
    "javascript/FileSystem.js~FileSystem#writeFile",
    "method"
  ]
]