RegisterPublic("OnGameModeInit","","GameModeInit");
RegisterPublic("OnGameModeExit","","GameModeExit");
RegisterPublic("OnFilterScriptInit","","FilterScriptInit");
RegisterPublic("OnFilterScriptExit","","FilterScriptExit");
RegisterPublic("OnPlayerConnect","i","PlayerConnect",["playerid"]);
RegisterPublic("OnPlayerDisconnect","ii","PlayerDisconnect",["playerid", "reason"]);
RegisterPublic("OnPlayerSpawn","i","PlayerSpawn",["playerid"]);
RegisterPublic("OnPlayerDeath","iii","PlayerDeath",["playerid", "killerid", "reason"]);
RegisterPublic("OnVehicleSpawn","i","VehicleSpawn",["vehicleid"]);
RegisterPublic("OnVehicleDeath","ii","VehicleDeath",["vehicleid", "killerid"]);
RegisterPublic("OnPlayerText","is","PlayerText",["playerid", "text"]);
RegisterPublic("OnPlayerCommandText","is","PlayerCommandText", true,["playerid", "cmdtext"]);
RegisterPublic("OnPlayerRequestClass","ii","PlayerRequestClass",["playerid", "classid"]);
RegisterPublic("OnPlayerEnterVehicle","iii","PlayerEnterVehicle",["playerid", "vehicleid", "ispassenger"]);
RegisterPublic("OnPlayerExitVehicle","ii","PlayerExitVehicle",["playerid", "vehicleid"]);
RegisterPublic("OnPlayerStateChange","iii","PlayerStateChange",["playerid", "newstate", "oldstate"]);
RegisterPublic("OnPlayerEnterCheckpoint","i","PlayerEnterCheckpoint",["playerid"]);
RegisterPublic("OnPlayerLeaveCheckpoint","i","PlayerLeaveCheckpoint",["playerid"]);
RegisterPublic("OnPlayerEnterRaceCheckpoint","i","PlayerEnterRaceCheckpoint",["playerid"]);
RegisterPublic("OnPlayerLeaveRaceCheckpoint","i","PlayerLeaveRaceCheckpoint",["playerid"]);
RegisterPublic("OnRconCommand","s","RconCommand", true,["cmd"]);
RegisterPublic("OnPlayerRequestSpawn","i","PlayerRequestSpawn",["playerid"]);
RegisterPublic("OnObjectMoved","i","ObjectMoved",["objectid"]);
RegisterPublic("OnPlayerObjectMoved","ii","PlayerObjectMoved",["playerid", "objectid"]);
RegisterPublic("OnPlayerPickUpPickup","ii","PlayerPickUpPickup",["playerid", "pickupid"]);
RegisterPublic("OnVehicleMod","iii","VehicleMod",["playerid", "vehicleid", "componentid"]);
RegisterPublic("OnEnterExitModShop","iii","EnterExitModShop",["playerid", "enterexit", "interiorid"]);
RegisterPublic("OnVehiclePaintjob","iii","VehiclePaintjob",["playerid", "vehicleid", "paintjobid"]);
RegisterPublic("OnVehicleRespray","iiii","VehicleRespray",["playerid", "vehicleid", "color1", "color2"]);
RegisterPublic("OnVehicleDamageStatusUpdate","ii","VehicleDamageStatusUpdate",["vehicleid", "playerid"]);
RegisterPublic("OnUnoccupiedVehicleUpdate","iiiffffff","UnoccupiedVehicleUpdate",["vehicleid", "playerid", "passenger_seat", "new_x", "new_y", "new_z", "vel_x", "vel_y", "vel_z"]);
RegisterPublic("OnPlayerSelectedMenuRow","ii","PlayerSelectedMenuRow",["playerid", "row"]);
RegisterPublic("OnPlayerExitedMenu","i","PlayerExitedMenu",["playerid"]);
RegisterPublic("OnPlayerInteriorChange","iii","PlayerInteriorChange",["playerid", "newinteriorid", "oldinteriorid"]);
RegisterPublic("OnPlayerKeyStateChange","iii","PlayerKeyStateChange",["playerid", "newkeys", "oldkeys"]);
RegisterPublic("OnRconLoginAttempt","ssi","RconLoginAttempt",["ip", "password", "success"]);
RegisterPublic("OnPlayerUpdate","i","PlayerUpdate",["playerid"]);
RegisterPublic("OnPlayerStreamIn","ii","PlayerStreamIn",["playerid", "forplayerid"]);
RegisterPublic("OnPlayerStreamOut","ii","PlayerStreamOut",["playerid", "forplayerid"]);
RegisterPublic("OnVehicleStreamIn","ii","VehicleStreamIn",["vehicleid", "forplayerid"]);
RegisterPublic("OnVehicleStreamOut","ii","VehicleStreamOut",["vehicleid", "forplayerid"]);
RegisterPublic("OnActorStreamIn","ii","ActorStreamIn",["actorid", "forplayerid"]);
RegisterPublic("OnActorStreamOut","ii","ActorStreamOut",["actorid", "forplayerid"]);
RegisterPublic("OnDialogResponse","iiiis","DialogResponse",["playerid", "dialogid", "response", "listitem", "inputtext"]);
RegisterPublic("OnPlayerTakeDamage","iifii","PlayerTakeDamage",["playerid", "issuerid", "amount", "weaponid", "bodypart"]);
RegisterPublic("OnPlayerGiveDamage","iifii","PlayerGiveDamage",["playerid", "damagedid", "amount", "weaponid", "bodypart"]);
RegisterPublic("OnPlayerGiveDamageActor","iifii","PlayerGiveDamageActor",["playerid", "damaged_actorid", "amount", "weaponid", "bodypart"]);
RegisterPublic("OnPlayerClickMap","ifff","PlayerClickMap",["playerid", "fX", "fY", "fZ"]);
RegisterPublic("OnPlayerClickTextDraw","ii","PlayerClickTextDraw",["playerid", "clickedid"]);
RegisterPublic("OnPlayerClickPlayerTextDraw","ii","PlayerClickPlayerTextDraw",["playerid", "playertextid"]);
RegisterPublic("OnIncomingConnection","isi","IncomingConnection",["playerid", "ip_address", "port"]);
RegisterPublic("OnTrailerUpdate","ii","TrailerUpdate",["playerid", "vehicleid"]);
RegisterPublic("OnVehicleSirenStateChange","iii","VehicleSirenStateChange",["playerid", "vehicleid", "newstate"]);
RegisterPublic("OnPlayerClickPlayer","iii","PlayerClickPlayer",["playerid", "clickedplayerid", "source"]);
RegisterPublic("OnPlayerSelectObject","iiiifff","PlayerSelectObject",["playerid", "type", "objectid", "modelid", "fX", "fY", "fZ"]);
RegisterPublic("OnPlayerWeaponShot","iiiifff","PlayerWeaponShot",["playerid", "weaponid", "hittype", "hitid", "fX", "fY", "fZ"]);
